services:
  backend:
    image: jwang17/simple-finance-server:latest
    build: ./server
    container_name: server
    env_file:
      - ./credentials
    networks:
      - simple-finance
    ports: 
      - "8000:8000"
    
  frontend:
    image: jwang17/simple-finance-frontend:latest
    build: ./frontend
    container_name: frontend
    networks:
      - simple-finance
    ports:
      - "3000:3000"


networks:
  simple-finance:
    driver: bridge