name: Build and Public Docker Image

on: [workflow_dispatch]

jobs:
    build_and_publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build the Docker images
              run: docker composer build

            - name: Publish frontend Docker image
              run: docker push jwang17/simple-finance-frontend:latest

            - name: Publish backend Docker image
              run: docker push jwang17/simple-finance-server:latest
