name: Build and Public Docker Image

on:
    workflow_dispatch:
    push:
        branches: jimmy-issue03-fix-docker-pipeline

    schedule:
        - cron: "30 14 * * 5"

jobs:
    build_and_publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build the Docker images
              run: docker compose build

            - name: Publish frontend Docker image
              run:
                  docker login -u jwang17 -p ${{ secrets.DOCKER_HUB_TOKEN  }} &&
                  docker push jwang17/simple-finance-frontend:latest

            - name: Publish backend Docker image
              run:
                  docker login -u jwang17 -p ${{ secrets.DOCKER_HUB_TOKEN  }} &&
                  docker push jwang17/simple-finance-server:latest
